name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.4.5'
      SERVERPOD_PASSWORD_database: 'meLFZdRMY3HudE4oDWx0MWSGhHV5Y-Od'
      SERVERPOD_PASSWORD_redis: 'ac6tlvS7AKyOL2v9fZ2hJu8VQc0ZPXPl'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: logixportal_server
        run: docker compose up --quiet-pull --quiet-build --build -d

      - name: Install dependencies
        working-directory: logixportal_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: logixportal_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: logixportal_server
        run: serverpod generate

      - name: Run tests
        working-directory: logixportal_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: logixportal_server
        run: docker compose down -v
